name: Deploy to Deno Deploy
on: 
  push:
    branches: [main]

  # to run this workflow manually on the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      
      - name: Build site
        run: hugo --minify

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "psotou"
          entrypoint: https://deno.land/std@0.140.0/http/file_server.ts
          root: public
